{{- if .Values.persistentVolume }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: buildkit-service-pvc
  namespace: {{ .Release.Namespace }}
  {{- if .Values.persistentVolume.annotations }}
  annotations:
    {{- toYaml .Values.persistentVolume.annotations | nindent 4 }}
  {{- end }}
spec:
  resources:
    requests:
      storage: {{ .Values.persistentVolume.size }}
  storageClassName: {{ .Values.persistentVolume.storageClass }}
  accessModes: [ "ReadWriteOnce" ]
{{- end }}
